# Generated by Django 5.2.13 on 2026-05-07 03:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_admin_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_snapshot', models.ImageField(upload_to='inference/snapshots/')),
                ('detection_results', models.JSONField(default=dict)),
                ('latency_ms', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('system_decision', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10)),
                ('operator_override', models.BooleanField(default=False)),
                ('operator_comment', models.TextField(blank=True)),
                ('final_decision', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('stream_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Operator Review'), ('APPROVED', 'Operator Approved'), ('REJECTED', 'Operator Rejected'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RetrainingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('LABELED', 'Labeled'), ('REJECTED', 'Rejected'), ('ADDED_TO_DATASET', 'Added to Training Dataset')], default='PENDING', max_length=20)),
                ('label_data', models.JSONField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('epochs', models.IntegerField(default=50)),
                ('batch_size', models.IntegerField(default=32)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('new_weights_path', models.FileField(blank=True, null=True, upload_to='models/weights/')),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_epoch', models.IntegerField(default=0)),
                ('logs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('OPERATOR', 'Operator')], default='OPERATOR', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='defectdetectionlog',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='defectdetectionlog',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='defectdetectionlog',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='modelevaluation',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='operatorsettings',
            name='operator',
        ),
        migrations.DeleteModel(
            name='SuperAdminSettings',
        ),
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='adminsettings',
            old_name='threshold',
            new_name='confidence_threshold',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='model_used',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.componenttype'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aimodel'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='avg_speed_ms',
            field=models.FloatField(default=0.0, help_text='Average inference latency in ms'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='compatible_components',
            field=models.ManyToManyField(blank=True, related_name='compatible_models', to='core.componenttype'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='file_path_engine',
            field=models.FileField(blank=True, null=True, upload_to='models/weights/'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='file_path_onnx',
            field=models.FileField(blank=True, null=True, upload_to='models/weights/'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='file_path_pt',
            field=models.FileField(blank=True, null=True, upload_to='models/weights/'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='input_size',
            field=models.IntegerField(default=640),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='is_deployment_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='last_deployed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='mAP',
            field=models.FloatField(default=0.0, help_text='Mean Average Precision'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='model_format',
            field=models.CharField(choices=[('PT', 'PyTorch (.pt)'), ('ONNX', 'ONNX (.onnx)'), ('ENGINE', 'TensorRT (.engine)')], default='PT', max_length=10),
        ),
        migrations.AddField(
            model_name='componenttype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['is_active', '-created_at'], name='core_aimode_is_acti_f58c53_idx'),
        ),
        migrations.AddField(
            model_name='inferencelog',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.componenttype'),
        ),
        migrations.AddField(
            model_name='inferencelog',
            name='model_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aimodel'),
        ),
        migrations.AddField(
            model_name='inferencelog',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retrainingqueue',
            name='labeled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labeled_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retrainingqueue',
            name='log_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.inferencelog'),
        ),
        migrations.AddField(
            model_name='datasetbuffer',
            name='retraining_queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_buffer', to='core.retrainingqueue'),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='base_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='core.aimodel'),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasetbuffer',
            name='training_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_samples', to='core.trainingjob'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DefectDetectionLog',
        ),
        migrations.DeleteModel(
            name='ModelEvaluation',
        ),
        migrations.DeleteModel(
            name='OperatorSettings',
        ),
        migrations.AddIndex(
            model_name='inferencelog',
            index=models.Index(fields=['operator', '-timestamp'], name='core_infere_operato_adb19c_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencelog',
            index=models.Index(fields=['session_id', '-timestamp'], name='core_infere_session_795018_idx'),
        ),
    ]
