# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datasetbuffer_inferencelog_retrainingqueue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencelog',
            name='operator_review_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inferencelog',
            name='rejection_reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('MISSED_DEFECT', 'Missed a defect'),
                    ('FALSE_POSITIVE', 'False positive'),
                    ('BLURRY_CAPTURE', 'Blurry capture'),
                    ('BAD_ANNOTATION', 'Bad annotation'),
                    ('WRONG_CLASS', 'Wrong class'),
                    ('OTHER', 'Other'),
                ],
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name='inferencelog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
