# Generated by Django 5.2.13 on 2026-05-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_align_default_admin_roles'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activeconfiguration',
            new_name='core_active_operato_1a84db_idx',
            old_name='core_active_operator_idx',
        ),
        migrations.RenameIndex(
            model_name='activeconfiguration',
            new_name='core_active_product_40f62c_idx',
            old_name='core_active_product_idx',
        ),
    ]
