# Generated by Django 5.2.13 on 2026-05-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_active_operator_idx_core_active_operato_1a84db_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('OPERATOR', 'Operator'), ('INSPECTOR', 'Inspector')], default='OPERATOR', max_length=20),
        ),
    ]
