# Generated by Django 5.2.13 on 2026-05-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencelog',
            name='defect_area_percent',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='inferencelog',
            name='segmentation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
