# Generated by Django 5.2.13 on 2026-05-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_inferencelog_defect_area_percent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminSettings',
        ),
    ]
