# Generated by Django 5.2.13 on 2026-05-08 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_adminsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inferencelog',
            index=models.Index(fields=['component', '-timestamp'], name='core_infere_compone_be1f3f_idx'),
        ),
    ]
