# Generated by Django 5.2.13 on 2026-05-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_align_default_admin_roles"),
        ("core", "0012_inferencelog_core_infere_compone_be1f3f_idx"),
    ]

    operations = []
