# Generated by Django 5.2.13 on 2026-05-14 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20260508_1458'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingOrderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturing_order', models.CharField(db_index=True, max_length=100, unique=True)),
                ('product_count', models.IntegerField(default=1, help_text='Current product index in the MO batch')),
                ('total_product_count', models.IntegerField(blank=True, default=0, help_text='Total products expected in MO')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('odoo_mo_id', models.CharField(blank=True, help_text='Odoo MO ID for API sync', max_length=100)),
                ('odoo_product_id', models.CharField(blank=True, help_text='Odoo Product ID', max_length=100)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='inferencelog',
            name='is_confidence_below_threshold',
            field=models.BooleanField(default=False, help_text='Flagged when confidence is too low on both PASS/FAIL classifications'),
        ),
        migrations.AddField(
            model_name='inferencelog',
            name='manufacturing_order',
            field=models.CharField(blank=True, db_index=True, help_text='Manufacturing Order (MO) identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='inferencelog',
            name='final_decision',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error - Manual Review Required')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inferencelog',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('MISSED_DEFECT', 'Missed a defect'), ('FALSE_POSITIVE', 'False positive'), ('BLURRY_CAPTURE', 'Blurry capture'), ('BAD_ANNOTATION', 'Bad annotation'), ('WRONG_CLASS', 'Wrong class'), ('CONFIDENCE_BELOW_THRESHOLD', 'Confidence below threshold (requires manual review)'), ('OTHER', 'Other')], max_length=60),
        ),
        migrations.AlterField(
            model_name='inferencelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Operator Review'), ('APPROVED', 'Operator Approved'), ('REJECTED', 'Operator Rejected'), ('ERROR', 'Error - Flagged for Manual Review'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='inferencelog',
            name='system_decision',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error - Manual Review Required')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='inferencelog',
            index=models.Index(fields=['manufacturing_order', '-timestamp'], name='core_infere_manufac_756159_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencelog',
            index=models.Index(fields=['status', '-timestamp'], name='core_infere_status_fc9646_idx'),
        ),
        migrations.AddField(
            model_name='manufacturingordersession',
            name='active_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aimodel'),
        ),
        migrations.AddField(
            model_name='manufacturingordersession',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mo_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activeconfiguration',
            name='manufacturing_orders',
            field=models.ManyToManyField(blank=True, help_text='MOs that can use this model configuration', related_name='active_configs', to='core.manufacturingordersession'),
        ),
        migrations.AddField(
            model_name='manufacturingordersession',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.componenttype'),
        ),
        migrations.AlterField(
            model_name='activeconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_active_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='manufacturingordersession',
            index=models.Index(fields=['manufacturing_order', '-started_at'], name='core_manufa_manufac_c9685b_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingordersession',
            index=models.Index(fields=['operator', 'is_active'], name='core_manufa_operato_d54fb6_idx'),
        ),
    ]
