# Generated by Django 5.2.14 on 2026-05-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20260508_1458'),
        ('core', '0013_merge_20260508_2049'),
    ]

    operations = [
    ]
