# Generated by Django 5.2.13 on 2026-05-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20260508_2049'),
        ('core', '0014_manufacturingordersession_and_more'),
    ]

    operations = [
    ]
