# Generated by Django 5.2.14 on 2026-05-27 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20260522_0001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingordersession',
            name='active_model',
        ),
        migrations.RemoveField(
            model_name='manufacturingordersession',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='manufacturingordersession',
            name='product',
        ),
        migrations.RemoveField(
            model_name='activeconfiguration',
            name='manufacturing_orders',
        ),
        migrations.RemoveIndex(
            model_name='inferencelog',
            name='core_infere_manufac_756159_idx',
        ),
        migrations.RemoveIndex(
            model_name='inferencelog',
            name='core_infere_status_fc9646_idx',
        ),
        migrations.AlterField(
            model_name='activeconfiguration',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_active_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inferencelog',
            name='manufacturing_order',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inferencelog',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('MISSED_DEFECT', 'Missed a defect'), ('FALSE_POSITIVE', 'False positive'), ('BLURRY_CAPTURE', 'Blurry capture'), ('BAD_ANNOTATION', 'Bad annotation'), ('WRONG_CLASS', 'Wrong class'), ('CONFIDENCE_BELOW_THRESHOLD', 'Confidence below threshold (requires manual review)'), ('OTHER', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=20),
        ),
        migrations.DeleteModel(
            name='ManufacturingOrderSession',
        ),
    ]
