# Generated by Django 5.2.14 on 2026-05-29 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_role_remapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inferencelog',
            options={'ordering': ['-batch_number', '-timestamp']},
        ),
        migrations.AddField(
            model_name='inferencelog',
            name='batch_number',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='inferencelog',
            index=models.Index(fields=['batch_number', '-timestamp'], name='core_infere_batch_n_67244c_idx'),
        ),
    ]
