# Generated by Django 5.2.14 on 2026-06-10

from django.db import migrations, models


def populate_batch_date_and_key(apps, schema_editor):
    InferenceLog = apps.get_model('core', 'InferenceLog')
    for log in InferenceLog.objects.all():
        batch_number = log.batch_number or 1
        batch_date = log.batch_date or log.timestamp.date()
        batch_key = log.batch_key or f"{batch_date.isoformat()}-{batch_number}"
        InferenceLog.objects.filter(pk=log.pk).update(
            batch_number=batch_number,
            batch_date=batch_date,
            batch_key=batch_key,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_normalize_inferencelog_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencelog',
            name='batch_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inferencelog',
            name='batch_key',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='inferencelog',
            index=models.Index(fields=['batch_date', '-batch_number', '-timestamp'], name='core_infere_batch_d_58ff28_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencelog',
            index=models.Index(fields=['batch_key'], name='core_infere_batch_k_1e4ebb_idx'),
        ),
        migrations.RunPython(populate_batch_date_and_key, migrations.RunPython.noop),
    ]
