# Generated by Django 5.2.14 on 2026-06-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_batch_date_and_batch_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inferencelog',
            options={'ordering': ['-batch_date', '-batch_number', '-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='inferencelog',
            name='core_infere_batch_n_67244c_idx',
        ),
        migrations.RenameIndex(
            model_name='inferencelog',
            new_name='core_infere_batch_d_36646a_idx',
            old_name='core_infere_batch_d_58ff28_idx',
        ),
        migrations.RenameIndex(
            model_name='inferencelog',
            new_name='core_infere_batch_k_29566d_idx',
            old_name='core_infere_batch_k_1e4ebb_idx',
        ),
        migrations.AddField(
            model_name='retrainingqueue',
            name='label_studio_exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retrainingqueue',
            name='label_studio_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
