# Generated by Django 5.2.14 on 2026-06-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_inferencelog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='is_deployed',
            field=models.BooleanField(default=False),
        ),
    ]
