# Generated by Django 5.2.14 on 2026-06-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_trainingjob_is_deployed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrainingqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('LABELED', 'Labeled'), ('REJECTED', 'Rejected'), ('ADDED_TO_DATASET', 'Added to Training Dataset'), ('TRAINED', 'Used in Training'), ('INVALID', 'Invalid Sample')], default='PENDING', max_length=20),
        ),
    ]
