$kind: http-request
name: GET Retrieve Configuration
method: GET
url: '{{baseUrl}}/api/core/admin-settings/{{configId}}/'
order: 3000
auth:
  type: bearer
  credentials:
    - key: token
      value: '{{accessToken}}'
