$kind: http-request
name: PUT Update Configuration
method: PUT
url: '{{baseUrl}}/api/core/admin-settings/{{configId}}/'
order: 4000
auth:
  type: bearer
  credentials:
    - key: token
      value: '{{accessToken}}'
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "operator": 1,
      "product": 1,
      "model": 1,
      "threshold": 0.6,
      "is_active": true
    }
